# Background and foreground colors
background = #f3e4cb
foreground = #4d2e1a

# Standard colors
palette = 0=#f3e4cb
palette = 1=#a4373c
palette = 2=#a46d2d
palette = 3=#a8611f
palette = 4=#a32f1a
palette = 5=#9c3521
palette = 6=#755833
palette = 7=#080503

# Bright colors
palette = 8=#9f8253
palette = 9=#d2656a
palette = 10=#d89b55
palette = 11=#e48e3e
palette = 12=#e84d31
palette = 13=#de553a
palette = 14=#b8884c
palette = 15=#4d2e1a
