$color = rgba(243, 228, 203, 1)
$inner_color = rgba(243, 228, 203, 0.66)
$outer_color = rgba(156, 53, 33, 1)
$font_color = rgba(77, 46, 26, 1)
$placeholder_color = rgba(77, 46, 26, 0.7)
$check_color = rgba(117, 88, 51, 1)
