background            #f3e4cb
foreground            #4d2e1a

# black
color0  #f3e4cb
color8  #9f8253

# red
color1  #a4373c
color9  #d2656a

# green
color2  #a46d2d
color10 #d89b55

# yellow
color3  #a8611f
color11 #e48e3e

# blue
color4  #a32f1a
color12 #e84d31

# magenta
color5  #9c3521
color13 #de553a

#cyan
color6  #755833
color14 #b8884c

#white
color7  #080503
color15 #4d2e1a


